config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :fotos

  root 'fotos#index'

end

app/models/foto.rb
class Foto < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/fotos_controller.rb
class FotosController < ApplicationController
  before_action :set_foto, only: [:show, :edit, :update, :destroy]

  # GET /fotos
  # GET /fotos.json
  def index
    @fotos = Foto.all
  end

  # GET /fotos/1
  # GET /fotos/1.json
  def show
  end

  # GET /fotos/new
  def new
    @foto = Foto.new
  end

  # GET /fotos/1/edit
  def edit
  end

  # POST /fotos
  # POST /fotos.json
  def create
    @foto = Foto.new(foto_params)

    respond_to do |format|
      if @foto.save
        format.html { redirect_to @foto, notice: 'Foto was successfully created.' }
        format.json { render :show, status: :created, location: @foto }
      else
        format.html { render :new }
        format.json { render json: @foto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fotos/1
  # PATCH/PUT /fotos/1.json
  def update
    respond_to do |format|
      if @foto.update(foto_params)
        format.html { redirect_to @foto, notice: 'Foto was successfully updated.' }
        format.json { render :show, status: :ok, location: @foto }
      else
        format.html { render :edit }
        format.json { render json: @foto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fotos/1
  # DELETE /fotos/1.json
  def destroy
    @foto.destroy
    respond_to do |format|
      format.html { redirect_to fotos_url, notice: 'Foto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foto
      @foto = Foto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def foto_params
      params.require(:foto).permit(:titulo, :descripcion, :imagen)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type.to_sym)} fade in") do
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message
            end)
    end
    nil
  end
end

app/helpers/fotos_helper.rb
module FotosHelper
end

app/views/fotos/_form.html.haml
= form_for @foto, :html => {:multipart => true} do |f|
  - if @foto.errors.any?
    #error_explanation
      %h2
        = pluralize(@foto.errors.count, "error")
        prohibited this foto from being saved:
      %ul
        - @foto.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :titulo
    %br/
    = f.text_field :titulo
  .field
    = f.label :descripcion
    %br/
    = f.text_area :descripcion
  .field
    = f.label :imagen
    %br/
    = f.text_field :imagen
  .actions
    = f.submit

app/views/fotos/edit.html.haml
%h1 Editing Foto
= render 'form'
= link_to 'Show', @foto
|
= link_to 'Back', fotos_path

app/views/fotos/index.html.haml
%h1 Listing Fotos
%table
  %thead
    %tr
      %th Titulo
      %th Descripcion
      %th Imagen
      %th{:colspan => "3"}
  %tbody
    - @fotos.each do |foto|
      %tr
        %td= foto.titulo
        %td= foto.descripcion
        %td= foto.imagen
        %td= link_to 'Show', foto
        %td= link_to 'Edit', edit_foto_path(foto)
        %td= link_to 'Destroy', foto, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Foto', new_foto_path

app/views/fotos/new.html.haml
%h1 New Foto
= render 'form'
= link_to 'Back', fotos_path

app/views/fotos/show.html.haml
%p
  %strong Titulo:
  = @foto.titulo
%p
  %strong Descripcion:
  = @foto.descripcion
%p
  %strong Imagen:
  = @foto.imagen
= link_to 'Edit', edit_foto_path(@foto)
|
= link_to 'Back', fotos_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Fototeca
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    .navbar.navbar-default
      .container
        .navbar-header
          = link_to 'Fotos', fotos_path, :class => 'navbar-brand'
        %ul.nav.navbar-nav
          %li.active
            %a{:href => "/"} Inicio
        %p.navbar-text.pull-right
          - if user_signed_in?
            = current_user.email
            |
            \#{link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link'} |
            \#{link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'}
          - else
            = link_to "Sign up", new_user_registration_path, :class => 'navbar-link'
            |
            \#{link_to "Login", new_user_session_path, :class => 'navbar-link'}
    .container
      - if flash[:notice]
        .alert.alert-info
          = flash[:notice]
      - if flash[:alert]
        .alert.alert-danger
          = flash[:alert]
      = yield
    / /container